import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  sectionHeader: {
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 8,
  },
  card: {
    marginHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    padding: 16,
    marginBottom: 4,
  },
  cardLabel: { fontSize: 15, fontWeight: "500", marginBottom: 12 },
  themeRow: { flexDirection: "row", gap: 8 },
  themeChip: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1.5,
    alignItems: "center",
  },
  themeChipText: { fontSize: 14 },
  zoomHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  resetText: { fontSize: 14, fontWeight: "500" },
  zoomRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  zoomBtn: {
    width: 44,
    height: 44,
    borderRadius: 10,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  zoomBtnText: { fontSize: 24, fontWeight: "300", lineHeight: 28 },
  zoomLabel: { flex: 1, textAlign: "center", fontSize: 14 },
  addBtn: {
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    paddingVertical: 14,
    alignItems: "center",
  },
  addBtnText: { fontSize: 15, fontWeight: "600" },
  colorRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  colorCard: {
    width: "31%",
    aspectRatio: 1,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  colorSwatch: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 6,
  },
  colorName: { fontSize: 12, fontWeight: "500", textAlign: "center" },
  disabledText: { fontSize: 13, fontStyle: "italic", marginTop: 4 },
});

